version: "3.2"

services:
  selenium-hub:
    image: selenium/hub:3.141.59-20210311
    ports:
      - "4444:4444"
#    networks:
#      - frontend

  firefox:
    image: selenium/standalone-firefox
    environment:
      HUB_HOST: selenium-hub
      JAVA_OPTS: "-Dselenium.LOGGER.level=WARNING"
    env_file: .env
#    networks:
#      - frontend
    expose:
      - "5555"

  accept:
    image: IMAGE_TESTS
    env_file: .env
#    networks:
#      - frontend

  smtp:
    image: schickling/mailcatcher
    container_name: mailcatcher
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    restart: on-failure
#    networks:
#      - backend
#      - frontend
    ports:
      - 1080:1080


